# Generated by Django 4.2.3 on 2023-07-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_App', '0002_alter_profilis_logotipas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projektas',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='projektas',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
